/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jcrupp' at '3/30/16 2:42 PM' with Gradle 2.12
 *
 * @author jcrupp, @date 3/30/16 2:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
